### ISSUE TITLE
Support for gnome-shell 3.21

### ISSUE THREAD

**Issue by frague59** [tomflannaghan/proxy-switcher#10]
This extension is very cool, I use it every days (computer used in a corporate network and at home)
Since the upgrade of gnome-shell to 3.21, it doesn't not work anymore...
Could you upgrade it to 3.21 shell ? Thanks !

**Comment by tomflannaghan** [comment]
I think I've done this for 3.21.91. Subsequent versions won't require the version check to pass by default. See https://mail.gnome.org/archives/gnome-announce-list/2016-September/msg00012.html
