### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by stejoo** [tomflannaghan/proxy-switcher#18]
Hi,

Thank you for creating this extension. I have been using it for quite a while, it's been helpful.
I noticed you updated the shell-version list by adding support for `40`.
Could I trouble you to "release" a new version by adding the appropriate tag?

I don't install the plugin via extensions.gnome.org but have an Ansible Playbook grab the latest release .zip of a plugin directly from GitHub (here). I could change it to grab `master`, which would work fine, but at the same time would be a sort of moving target. I'd much rather grab a known good release instead of a a moving branch.

Thanks again for the plugin :+1:

**Comment by tomflannaghan** [comment]
Hi @stejoo I've created a release [1.3](https://github.com/tomflannaghan/proxy-switcher/releases/tag/1.3) with the latest version including the support for gnome 40. Sorry I didn't make one before when I released the gnome 40 support on extensions.gnome.org - will try to remember to do that next time I update it. Glad you like the plugin, and if you have any issues with the release I created, please let me know!

**Comment by stejoo** [comment]
Great, i'll use that version from this point forward.
Thanks for responding and acting so quickly. :+1:
