### ISSUE TITLE
Proxy switcher does not show up in menu (anymore) after Debian upgrade to bookworm/testing

### ISSUE THREAD

**Issue by rduivenvoorde** [tomflannaghan/proxy-switcher#19]
I've used the extension for a long time sucessfully.

After the latest Debian release (I run testing, so going from Bullseye to Bookworm), I cannot make ProxySwitcher work anymore, it seems not to show up anymore.
Tried to remove it manually, install it via the browser, and install it manually. But it stays hidden from my menu.
BUT on another laptop it showed up after the upgrades...

Running `gnome-shell --version` shows me `40.4`, so I tried to add that version in the metadata.json

Running ALt-F2 / lg (tookinglass) does NOT show me any errors.

Anybody a hint on how to debug this?

Currently running 'Gnome Classic', but tried 'X Server' too

Any help appreciated

**Comment by rduivenvoorde** [comment]
Argh, creating a fresh user/profile and it just works in that one...
What can possibly hide or not start it?

**Comment by rduivenvoorde** [comment]
Argh2, apparently 'something' has switched off all extensions.
Running the 'Extensions' app (green jigsaw puzzle piece), the upper top switch was disabled... Enabling it (making it blue), and Proxy Switcher (and Screenshot Tool) showed up.

Sorry for the fuzz, will close this.

**Comment by tomflannaghan** [comment]
@rduivenvoorde no worries about the fuss, exactly this thing happened to me too after an upgrade (I use Fedora). Glad you fixed it!
