### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mehmetkurucali** [tomflannaghan/proxy-switcher#21]
It was working before but disappeared by itself. It no longer loads.

**Comment by tomflannaghan** [comment]
Hi @mehmetkurucali could this be the same problem as in #19? I also experienced it on Fedora so it's not specific to a distro - was probably an update to some package somewhere.

Could you go into the Gnome Extensions app (within Gnome, not the website) and check that Gnome extensions are enabled and that the Proxy Switcher extension is enabled?

**Comment by keighrim** [comment]
Experiencing the same problem. I think it started with gnome 41 (arch). I can't turn the extension back on via extensions app, as it shows a scary error icon and the button is not clickable.
![Screenshot from 2021-12-07 18-43-46](https://user-images.githubusercontent.com/9062727/145005820-c4bb2a0f-e0a9-423b-ae32-7451700f482e.png)
