### ISSUE TITLE
When will extensions.gnome.org be updated?

### ISSUE THREAD

**Issue by xiaozhangup** [tomflannaghan/proxy-switcher#25]
First of all, thank you for your attention to the problem and the quick fix.
I've tested it on my computer and the problem has been solved, so I think it's ready to be updated at extensions.gnome.org

**Comment by tomflannaghan** [comment]
I've already uploaded the extension to extensions.gnome.org. It typically takes a few hours to a day for them to review the code change before it is available to users.

**Comment by xiaozhangup** [comment]
> ‎我已经将扩展程序上传到 extensions.gnome.org。他们通常需要几个小时到一天的时间才能查看代码更改，然后才能将其提供给用户。‎

I see,thanks!

**Comment by tomflannaghan** [comment]
The fix has now been reviewed and is available on extensions.gnome.org
