### ISSUE TITLE
THANK YOU !

### ISSUE THREAD

**Issue by rduivenvoorde** [tomflannaghan/proxy-switcher#29]
Hi Tom,

THANKS!! 

(was afraid you would get tired of api/version changes)

Managed to make your (to me super valuable) extension work again on Debian Testing / Gnome 43!!

(took me some fiddling with the extension manager complaining about "Your native host connector do not support following APIs: v6. Probably you should upgrade native host connector or install plugins for missing APIs. Refer [documentation](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation) for instructions." but just removing and adding again all works)

![Screenshot from 2022-11-07 10-42-34](https://user-images.githubusercontent.com/731673/200278517-00d00dfe-0330-4ba7-b023-32d9e3fc8ff0.png)

**Comment by tomflannaghan** [comment]
@TravMurav kindly made it work with the new Gnome version, so they deserve the thanks! Was much appreciated!
