### ISSUE TITLE
Compatibility with GNOME Shell 44

### ISSUE THREAD

**Issue by simonspa** [tomflannaghan/proxy-switcher#30]
Dear @tomflannaghan 

is there any chance you could take the time and make this compatible with the latest GNOME Shell 44, now shipping with Ubuntu 23.04 Lunar Lobster?

This extension is a huge relieve when having to change proxies often...

All the best,
Simon

**Comment by tomflannaghan** [comment]
Hi @simonspa , I've made it compatible in 51b7d49. I've submitted to the Extensions site, so once the change is approved it should also be available there.

**Comment by simonspa** [comment]
Wow :heart_eyes: thank you so much!
