### ISSUE TITLE
Clicking on the pill Icon

### ISSUE THREAD

**Issue by AmirHosseinNiknezhad** [tomflannaghan/proxy-switcher#33]
Thank you for this great project. It improves my workflow a lot. I have a small suggestion for improvement. It would be nice if clicking on the pill icon in the menu could toggle the proxy mode between off and manual or automatic (depending on the previous state). I think this would be convenient and useful, as I often switch between off and manual modes, and I guess many others do too (or off and automatic). All the shell's built-in quick settings pill icons already have some useful functionality when clicked as that's very convenient, and it would be consistent and useful to have the same for ours.

**Comment by tomflannaghan** [comment]
Thanks for the suggestion - I totally agree that would be useful. I'll try to implement at the weekend.

**Comment by KonstantinHirsch** [comment]
I second @AmirHosseinNiknezhad , this would be a great feature. Thanks for your work!

**Comment by tomflannaghan** [comment]
I've now resolved this in #36, and uploaded to the extensions site. It'll take a few hours/day to come through as will need to be reviewed. Please let me know if you find a problem with the new behaviour.
