### ISSUE TITLE
Please provide tagged release

### ISSUE THREAD

**Issue by sbrun** [tomflannaghan/proxy-switcher#4]
Hi,

It would be great if you could provide a tagged release. 
I'm packaging this extension for distro kali linux and the packaging tools works best with tagged release (we have tools that monitors web pages listing release, and it works well with github pages showing git tags).

Thanks

**Comment by tomflannaghan** [comment]
Hi there, it would be great to have this extension in kali linux :-) I've added a tagged release (v1.0). This is my first tagged release so please let me know if I've done it right or if you need more info.
Thanks!

**Comment by sbrun** [comment]
Hi,
Everything looks ok.
thanks

**Comment by tomflannaghan** [comment]
Great. Thanks!
