### ISSUE TITLE
Error with gnome 3.18

### ISSUE THREAD

**Issue by sbrun** [tomflannaghan/proxy-switcher#8]
Hi
This extension is used in Kali Linux and I would like to update the package for gnome-shell 3.18.0. 
I made a git clone today. I tried to install it but I've have these error message:
```
Gjs-Message: JS LOG: Extension "ProxySwitcher@flannaghan.com" had error: TypeError: this._switcherMenu.status is undefined
```
The version of gnome-shell is 3.18.0 (from debian testing). 

Can you help me?
thanks

**Comment by tomflannaghan** [comment]
I think I've tracked down this bug - was a change in the api for popup menus in gnome shell. I've pushed a fix that I've tested on Fedora 23 (which also uses gnome 3.18). Let me know if that has solved your problem. Thanks for reporting it!

**Comment by sbrun** [comment]
It solved my problem. Thanks a lot!
